### ISSUE TITLE
UPdate for Google Drive

### ISSUE THREAD

**Issue by hmrserver** [Ardakilic/backmeup#3]
Hello, Can you update it for google Drive API  too  please?

**Comment by Ardakilic** [comment]
Hello, 

I'm not using Google Drive much, but when I have time I'll look into it! 👍 

I'd also appreciate the pull requests if anyone wants to contribute 🎉

**Comment by Ardakilic** [comment]
Sorry, I'm qute full with all the work. I'll be using https://github.com/prasmussen/gdrive when I implement this for future releases. Sadly, GDrive stores folder names as ID, so folder name cannot be used directly. I need to find a workaround for this (maybe list|grep|awk and get id etc.)

**Comment by hmrserver** [comment]
Hello, can you add Hacktoberfest tag so users interested from Hacktoberfest community can reach to this and can help in the process?

**Comment by Ardakilic** [comment]
@hmrserver sure! Any guides, or would adding #hacktoberfest to repo description suffice?

**Comment by hmrserver** [comment]
I guess adding "hacktoberfest" label to this issue would be enough (like you added enhancement one).

**Comment by Ardakilic** [comment]
@hmrserver done!

**Comment by hmrserver** [comment]
Great!
Btw if you want then you can look at my https://github.com/hmrserver/GBackup .. I had added this to my script which does the task(atleast for CentOS).
Since I really liked your version more ;)

**Comment by Ardakilic** [comment]
@hmrserver Aha, thanks for the heads-up! I can see you've implemented the folder finding method on your script, I'll definitely look for this soon.

By the way, any reason you're downloading `gdrive` from Google Drive directly?

**Comment by hmrserver** [comment]
I had copied the link from the main gdrive repo (I guess): https://github.com/prasmussen/gdrive you can see it's readme.
Which I felt would be nice enough.

**Comment by islander** [comment]
Check my implementation https://github.com/Ardakilic/backmeup/pull/6

**Comment by Ardakilic** [comment]
This is implemented with PR #6 , thanks to @islander . Please see the master branch for this implementation.
