### ISSUE TITLE
Alternative - duply

### ISSUE THREAD

**Issue by ad-m** [Ardakilic/backmeup#4]
Hello,

By analysis use cases and missing features I would like add info about alternative [duply](https://duply.net). It's python script.

It support all uses case:

- [x] The script dumps all of your MySQL databases individually. - Yes, through by ``pre`` script
- [x] The script backs up all of your Web files (e.g: root of all of your virtual hosts). - Yes.
- [x] The script compresses your web-root and databases to a single archive. - It does it better because it splits into multiple archives, which secures itself against transmission problems.
- [x]     The script uploads the compressed archive into a folder in your Dropbox account, Amazon S3 bucket or Owncloud Server.
- [x]     If the method is set to dropbox, The script makes sure that you always have the newest Dropbox-Uploader script. - Not applicable.
- [x]     After the upload, the script cleans up the temporary files (dumps, the archive itself). - Works better because it stores only a portion of the archive at a time.

It support all missing features:

- [x]     Tests on CentOS, Arch etc. - Yes, a lot of distro ships packages.
- [x]     Mega.nz integration - Yes.
- [x]     Owncloud Integration - Yes.
- [x]     AWS S3 integration - Yes.
- [x]     Increased security? - Yes, encryption.
- [x]     Reading configuration from an external file - Yes.
- [x]     Postgres support - Yes, throught ``pre`` script.
- [x]     Option to dump only the database(s) or only Virtualhost files - Yes.
- [x]     Multiple Virtualhost folder support - Yes, dump any target as you want.

Greetings,

**Comment by Ardakilic** [comment]
Hello,

Thanks for the suggestion. As far as I can see [duply is a shell script, not python](https://sourceforge.net/p/ftplicity/code/HEAD/tree/duply/trunk/duply.sh), which actually is a [frontend of another python script, duplicity](https://code.launchpad.net/duplicity), [as they say](http://duply.net/wiki/index.php/Duply-documentation). Also, half of the missing features were ~~strikethrough~~, so already half of them are done already. 

This script is a solo project of mine, which I do on my spare time for my personal needs. I'm not trying to make this script a Swiss army knife, but I'd love to consider any kind of contributions.

Thank you. I'll check both scripts' source codes and look how they handled stuff, maybe implement / better this one.

**Comment by ad-m** [comment]
Yes, I have made some simplifications regarding the technology and dependence of this project. However, in most environments this does not have any practical significance.

I actively use duply on several VPS servers. I used it with different file storage locations. For me, it is very important that you can painlessly change your service provider and protocol. A large supplier list is provided. 

I used to use S3. Today I did not worry about using sftp, because I had such an environment.

The program has an incremental backup mechanism and their verification (as if it recovers files, but only compares their contents and prints them differently). This is related to the ability to recover any file from any time by downloading only some archives (metadata seperated).

For full features list see http://duplicity.nongnu.org/duplicity.1.html .
