### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by silverbux** [Ardakilic/backmeup#5]
hi im getting this error on **Ubuntu 16.04.3 LTS**

```
/usr/bin/env: ‘bash\r’: No such file or directory
```

**Comment by Ardakilic** [comment]
Hey @silverbux 

I believe it's because of new line endings (which works fore me in Ubuntu weirdly though) in the script.

As a quick fix, can you please run this, and try to execute the backmeup.unix.sh instead? 

```bash
sed $'s/\r$//' ./backmeup.sh > ./backmeup.unix.sh
```

Or this:

```bash
dos2unix backmeup.sh
```

If it works, I'll try to release an updated version.

**Comment by silverbux** [comment]
@Ardakilic hi thanks for the reply,
the /usr/bin/env error is gone and it seems to generate the backup file now

but the problem is it's not uploading to dropbox, and i think it has something to do with "filename".
i think it creates this weird character in that unix cant read

because right now i cant event delete the files. you'll notice in the screenshot it has "?" in the beginning of the filename.

im not sure if it really is the problem though

![image](https://user-images.githubusercontent.com/1888261/36405485-f7c1e468-162b-11e8-86df-d896aff31186.png)

**Comment by Ardakilic** [comment]
@silverbux 

Which way did you use to convert the file? Sed or dos2unix? Can you try the other way around?

https://github.com/Ardakilic/backmeup/blob/7e7c7ce21890b4d75f5e3655153268bbdd30eb2b/backmeup.sh#L182

https://github.com/Ardakilic/backmeup/blob/7e7c7ce21890b4d75f5e3655153268bbdd30eb2b/backmeup.sh#L184

There's nothing as a prefix to the filename. I need to investigate a bit more.

I'll try to run on a fresh Ubuntu VM today and let you know if I encounter.

Also, you can delete the files like this:

```bash
find . -name "*.tar.gz" -type f -delete
```

or

```bash
rm "*.tar.gz"
```

etc. Either one should work.

**Comment by silverbux** [comment]
hey @Ardakilic  thanks for the reply

i used dos2unix

it was weird but i was able to solved it by just grabing an old copy of backmeup.sh and uploading it to server.

i still havent figure out what went wrong though
